# Generated by Django 6.0.2 on 2026-03-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('dropped', 'Dropped'), ('completed', 'Completed'), ('waitlisted', 'Waitlisted'), ('pending_payment', 'Pending Payment')], default='active', max_length=20),
        ),
    ]
