# Generated by Django 6.0.2 on 2026-03-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_alter_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('dropped', 'Dropped'), ('completed', 'Completed'), ('waitlisted', 'Waitlisted'), ('pending_payment', 'Pending Payment'), ('pending_approval', 'Pending Approval')], default='active', max_length=20),
        ),
    ]
