# Generated by Django 6.0.2 on 2026-03-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_date',
            field=models.DateField(db_index=True),
        ),
    ]
