# Generated by Django 6.0.2 on 2026-03-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='auto_revision_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
