# Generated by Django 6.0.2 on 2026-03-16 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_auto_revision_enabled'),
        ('quizzes', '0004_quiz_is_daily_dailyquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_revision',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RevisionQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics_covered', models.TextField(help_text='Comma separated list of topics')),
                ('date_generated', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_quizzes', to='courses.course')),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision_assignment', to='quizzes.quiz')),
            ],
        ),
    ]
