# Generated by Django 6.0.2 on 2026-03-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_quiz_is_revision_revisionquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionquiz',
            name='title',
            field=models.CharField(default='Revision Quiz', max_length=255),
        ),
    ]
