# Generated by Django 6.0.2 on 2026-03-17 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_group_instructor'),
        ('quizzes', '0006_revisionquiz_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Leave blank to make available to all batches of this course.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.batch'),
        ),
    ]
