# Generated by Django 6.0.2 on 2026-03-17 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_group_instructor'),
        ('resources', '0003_resourceview'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileresource',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Make available only to a specific group (e.g. for projects).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.group'),
        ),
    ]
