from django.db import models
from django.conf import settings


class Course(models.Model):
    """A course offered by the college."""

    class Status(models.TextChoices):
        ACTIVE = 'active', 'Active'
        INACTIVE = 'inactive', 'Inactive'
        ARCHIVED = 'archived', 'Archived'

    title = models.CharField(max_length=200)
    code = models.CharField(max_length=20, unique=True)
    description = models.TextField(blank=True)
    instructor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name='courses_teaching',
        limit_choices_to={'role__in': ['instructor', 'admin']},
    )
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.ACTIVE)
    thumbnail = models.ImageField(upload_to='course_thumbnails/', blank=True, null=True)
    credits = models.PositiveSmallIntegerField(default=3)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    auto_revision_enabled = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.code} – {self.title}"


class Batch(models.Model):
    """A specific run/section of a course (e.g. Jan 2025 cohort)."""

    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='batches')
    name = models.CharField(max_length=100)          # e.g. "Batch A", "Jan 2025"
    start_date = models.DateField()
    end_date = models.DateField()
    max_students = models.PositiveIntegerField(default=30)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-start_date']
        verbose_name_plural = 'Batches'

    def __str__(self):
        return f"{self.course.code} – {self.name}"

    @property
    def enrolled_count(self):
        return self.enrollments.count()

    @property
    def is_full(self):
        return self.enrolled_count >= self.max_students


class Group(models.Model):
    """A sub-group within a batch for project/lab work."""

    batch = models.ForeignKey(Batch, on_delete=models.CASCADE, related_name='groups')
    name = models.CharField(max_length=100)
    members = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='course_groups',
        blank=True,
        limit_choices_to={'role': 'student'},
    )
    instructor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='groups_teaching',
        limit_choices_to={'role__in': ['instructor', 'admin']},
    )

    def __str__(self):
        return f"{self.batch} – {self.name}"


class Announcement(models.Model):
    """Important notices posted for a course or specific batch."""
    title = models.CharField(max_length=200)
    content = models.TextField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='announcements')
    batch = models.ForeignKey(Batch, on_delete=models.CASCADE, related_name='announcements', null=True, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title


class Lesson(models.Model):
    """A lesson within a course, possibly generated by AI."""
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='lessons')
    title = models.CharField(max_length=200)
    content = models.TextField()  # Markdown or HTML
    generated_by_ai = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_at']

    def __str__(self):
        return f"{self.course.code} – {self.title}"
